version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    networks:
      - node-red-net
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mqtt-data:/mosquitto/data
      - ./docker/mqtt-config:/mosquitto/config
      - ./docker/mqtt-log:/mosquitto/log

  node-red:
    build: ./docker/node-red/
    image: node-red-mysql/node-red:latest
    networks:
      - node-red-net
    ports:
      - "1880:1880"
    volumes:
      - ./docker/node-red-data:/data
    environment:
      - TZ=Europe/Oslo
    depends_on:
      - mqtt
      - mariadb

  mariadb:
    image: yobasystems/alpine-mariadb
    env_file:
      - ./docker/mariadb-config/db.env
    volumes:
      - ./docker/mariadb-data:/var/lib/mysql
      - ./docker/mariadb-config/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - node-red-net
    ports:
      - "3306:3306"

networks:
  node-red-net:

volumes:
  mosquitto_data:
  mosquitto_config:
  mosquitto_log:
  nodered_data:
  mariadb_data:
  